const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
process.env.DB_DRIVER='pglite';process.env.DB_PATH='memory://';process.env.NODE_ENV='test';for(const k of ['JWT_ACCESS_SECRET','JWT_REFRESH_SECRET','JWT_CUSTOMER_SECRET','SETUP_KEY'])process.env[k]=crypto.randomBytes(32).toString('hex');
const db=require('../src/config/db'),H=require('../src/services/erp.helpers');let server,url,token,cashierToken,product,supplier,customer,sale,purchase;const key=()=>crypto.randomUUID();
async function req(path,body,method='POST',auth=token){const res=await fetch(url+'/api/v1'+path,{method,headers:{...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(auth?{Authorization:'Bearer '+auth}:{})},body:body?body instanceof FormData?body:JSON.stringify(body):undefined});let data;try{data=await res.json();}catch{data={};}return{status:res.status,...data};}
async function good(path,body,method='POST',auth=token){const r=await req(path,body,method,auth);assert.ok(r.status>=200&&r.status<300,`${path}: ${JSON.stringify(r)}`);return r.data;}
before(async()=>{await require('../scripts/migrate')();server=require('../src/app').listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));url='http://127.0.0.1:'+server.address().port;await good('/auth/setup',{setupKey:process.env.SETUP_KEY,fullName:'ERP Test Owner',username:'owner',password:'Testing-Only-Long-Password',storeName:'Test Grocery',state:'Uttarakhand',stateCode:'05',gstin:'05AAAAA0000A1Z5',registrationType:'regular',address:'Test address'},'POST',null);token=(await good('/auth/login',{username:'owner',password:'Testing-Only-Long-Password'},'POST',null)).accessToken;});
after(async()=>{await new Promise(r=>server.close(r));await db.pool.end();});
test('Decimal GST calculations: inclusive, exclusive, interstate and fractional quantities',()=>{const x=H.lineTax({qty:1,rate:118,gst:18,inclusive:true});assert.equal(x.total_amount,118);assert.equal(x.taxable_amount,100);assert.equal(x.cgst_amount,9);assert.equal(x.sgst_amount,9);const y=H.lineTax({qty:.5,rate:100,gst:5,interstate:true});assert.equal(y.total_amount,52.5);assert.equal(y.igst_amount,2.5);assert.equal(y.cgst_amount,0);});
test('First owner setup and authentication protections',async()=>{assert.equal((await req('/auth/setup',{setupKey:process.env.SETUP_KEY,password:'Testing-Only-Long-Password'})).status,409);assert.equal((await req('/auth/login',{username:'owner',password:'wrong'})).status,401);assert.equal((await req('/erp/dashboard',null,'GET',null)).status,401);});
test('Masters and role setup',async()=>{supplier=await good('/suppliers',{companyName:'Test Distributor',supplierCode:'TEST-SUP',registrationType:'regular',stateCode:'05',state:'Uttarakhand',gstin:'05AAAAA0000A1Z5',pan:'AAAAA0000A'});customer=await good('/customers',{name:'Test Customer',stateCode:'05',creditLimit:500});product=await good('/products',{name:'Test Rice 1kg',localName:'टेस्ट चावल',sku:'TEST-RICE',unitId:1,categoryId:1,hsnCode:'1006',gstRate:18,costPrice:100,mrp:130,salePrice:118,taxInclusive:true,storeId:1});await good('/users',{fullName:'Test Cashier',username:'cashier',password:'Cashier-Testing-Password',roleId:5,storeId:1});cashierToken=(await good('/auth/login',{username:'cashier',password:'Cashier-Testing-Password'},'POST',null)).accessToken;});
test('Purchase updates stock, weighted cost, GST and supplier payable atomically',async()=>{purchase=await good('/erp/purchases',{idempotencyKey:key(),storeId:1,supplierId:supplier.id,supplierInvoiceNo:'SUP-001',supplierInvoiceDate:H.today(),items:[{productId:product.id,quantity:10,freeQuantity:2,rate:100,gstRate:18,mrp:130,salePrice:118}],payments:[{mode:'bank',amount:180}]});assert.equal(Number(purchase.total_amount),1180);assert.equal(Number(purchase.cgst_amount),90);assert.equal(Number((await db.query('SELECT sum(current_qty) q FROM stock WHERE product_id=$1',[product.id])).rows[0].q),12);assert.equal(Number((await db.query('SELECT cost_price FROM products WHERE id=$1',[product.id])).rows[0].cost_price),83.33);assert.equal((await good('/erp/ledger/supplier/'+supplier.id,null,'GET')).balance,1000);});
test('Duplicate supplier invoice rolls back all changes',async()=>{const b={idempotencyKey:key(),storeId:1,supplierId:supplier.id,supplierInvoiceNo:'SUP-001',supplierInvoiceDate:H.today(),items:[{productId:product.id,quantity:1,rate:100,gstRate:18}]};assert.equal((await req('/erp/purchases',b)).status,409);assert.equal(Number((await db.query('SELECT count(*) n FROM purchases')).rows[0].n),1);assert.equal(Number((await db.query('SELECT sum(current_qty) q FROM stock')).rows[0].q),12);});
test('Cashier cannot see cost/profit, grant access or apply unauthorized discounts',async()=>{const catalog=await good('/erp/catalog?storeId=1',null,'GET',cashierToken);assert.equal(catalog[0].cost_price,undefined);assert.equal((await req('/erp/settings',null,'GET',cashierToken)).status,403);assert.equal((await req('/erp/reports/profit',null,'GET',cashierToken)).status,403);assert.equal((await req('/erp/sales/quote',{storeId:1,items:[{productId:product.id,quantity:1,discountPct:5}]},'POST',cashierToken)).status,403);});
test('POS sale and retry produce one invoice and one stock deduction',async()=>{const b={idempotencyKey:key(),storeId:1,items:[{productId:product.id,quantity:2}],payments:[{mode:'cash',amount:236}]};sale=await good('/erp/sales',b,'POST',cashierToken);assert.equal(Number(sale.total_amount),236);assert.equal((await good('/erp/sales',b,'POST',cashierToken)).id,sale.id);assert.equal(Number((await db.query('SELECT sum(current_qty) q FROM stock')).rows[0].q),10);const detail=await good('/erp/sales/'+sale.id,null,'GET',cashierToken);assert.equal(detail.items[0].cost_price_snapshot,undefined);assert.equal(detail.items[0].snapshot.local_name,'टेस्ट चावल');assert.equal((await good('/erp/reports/profit',null,'GET')).rows[0].gross_profit,33.34);});
test('Overselling and duplicate cart rows cannot overdraw stock',async()=>{for(const items of [[{productId:product.id,quantity:11}],[{productId:product.id,quantity:6},{productId:product.id,quantity:6}]])assert.equal((await req('/erp/sales',{idempotencyKey:key(),storeId:1,items,payments:[]})).status,409);assert.equal(Number((await db.query('SELECT sum(current_qty) q FROM stock')).rows[0].q),10);});
test('Customer credit limit and receipts',async()=>{await good('/erp/sales',{idempotencyKey:key(),storeId:1,customerId:customer.id,items:[{productId:product.id,quantity:1}],payments:[]});assert.equal((await good('/erp/ledger/customer/'+customer.id,null,'GET')).balance,118);assert.equal((await req('/erp/sales',{idempotencyKey:key(),storeId:1,customerId:customer.id,items:[{productId:product.id,quantity:4}],payments:[]})).status,400);await good('/erp/payments',{idempotencyKey:key(),storeId:1,partyType:'customer',partyId:customer.id,amount:100,mode:'upi'});assert.equal((await good('/erp/ledger/customer/'+customer.id,null,'GET')).balance,18);});
test('Sales return reverses stock/GST and rejects duplicate over-return',async()=>{const detail=await good('/erp/sales/'+sale.id,null,'GET');const b={idempotencyKey:key(),items:[{itemId:detail.items[0].id,quantity:1}],reason:'Returned sealed pack',refundMode:'cash'};assert.equal((await good('/erp/sales/'+sale.id+'/return',b)).amount,118);assert.equal((await good('/erp/sales/'+sale.id+'/return',b)).amount,118);assert.equal(Number((await db.query('SELECT sum(current_qty) q FROM stock')).rows[0].q),10);assert.equal((await req('/erp/sales/'+sale.id+'/return',{...b,idempotencyKey:key(),items:[{itemId:detail.items[0].id,quantity:2}]})).status,400);});
test('Expired stock excluded and branch transfer permissions enforced',async()=>{const batch=await H.insert(db,'product_batches',{product_id:product.id,batch_number:'EXPIRED',expiry_date:'2020-01-01'});await db.withTransaction(c=>H.movement(c,{storeId:1,productId:product.id,batchId:batch.id,qty:5,type:'opening',referenceType:'test',referenceId:1,userId:1}));assert.equal(Number((await good('/erp/catalog?storeId=1',null,'GET'))[0].total_stock),10);const store=await good('/erp/stores',{name:'Second store',stateCode:'05'});await good('/erp/transfers',{storeId:1,toStoreId:store.id,productId:product.id,quantity:2});assert.equal(Number((await good('/erp/catalog?storeId='+store.id,null,'GET'))[0].total_stock),2);assert.equal((await req('/erp/catalog?storeId='+store.id,null,'GET',cashierToken)).status,403);});
test('CSV import previews and commits once',async()=>{const f=new FormData();f.append('type','products');f.append('file',new Blob(['name,sku,unit,category,gstRate,costPrice,mrp,salePrice,openingStock\nTest Salt,TEST-SALT,pcs,Grocery,5,10,20,18,4\n']),'products.csv');const preview=await good('/imports/preview',f);assert.equal(preview.rows.length,1);const b={storeId:1,jobId:preview.jobId,rows:preview.rows};const committed=await good('/imports/commit-products',b);assert.equal(committed.created,1);assert.deepEqual(await good('/imports/commit-products',b),committed);});
test('GSTR-2B reconciles by GSTIN, invoice, date and tax components',async()=>{const f=new FormData();f.append('period',H.today().slice(0,7));f.append('storeId','1');f.append('file',new Blob([`gstin,invoiceNo,invoiceDate,taxable,cgst,sgst,igst\n05AAAAA0000A1Z5,SUP-001,${H.today()},1000,90,90,0\n`]),'gstr2b.csv');assert.equal((await good('/imports/gstr2b',f))[0].status,'Matched');});
test('Logout immediately revokes the server session',async()=>{await good('/auth/logout',{},'POST',cashierToken);assert.equal((await req('/erp/catalog?storeId=1',null,'GET',cashierToken)).status,401);});
