ALTER TABLE users ADD COLUMN token_version INT NOT NULL DEFAULT 0;
CREATE TABLE auth_sessions (id UUID PRIMARY KEY, user_id INT NOT NULL REFERENCES users(id), expires_at TIMESTAMPTZ NOT NULL, revoked BOOLEAN NOT NULL DEFAULT false);
ALTER TABLE stores ADD COLUMN registration_type TEXT NOT NULL DEFAULT 'unregistered';
ALTER TABLE stores ADD COLUMN invoice_prefix VARCHAR(5) NOT NULL DEFAULT 'INV';
ALTER TABLE stores ADD COLUMN receipt_footer TEXT NOT NULL DEFAULT 'Thank you. Please visit again.';
ALTER TABLE suppliers ADD COLUMN supplier_code TEXT UNIQUE;
ALTER TABLE suppliers ADD COLUMN registration_type TEXT NOT NULL DEFAULT 'unregistered';
UPDATE suppliers SET supplier_code='SUP-'||id, registration_type=CASE WHEN gstin IS NULL THEN 'unregistered' ELSE 'regular' END;
ALTER TABLE purchases ADD COLUMN supplier_snapshot JSONB;
ALTER TABLE purchases ADD COLUMN supplier_invoice_date DATE;
ALTER TABLE purchases ADD COLUMN place_of_supply VARCHAR(2);
ALTER TABLE purchases ADD COLUMN po_number TEXT;
ALTER TABLE purchases ADD COLUMN grn_number TEXT;
ALTER TABLE purchases ADD COLUMN due_date DATE;
ALTER TABLE purchases ADD COLUMN cess_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchases ADD COLUMN discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchases ADD COLUMN reverse_charge BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE purchases ADD COLUMN notes TEXT;
ALTER TABLE purchases ADD COLUMN idempotency_key TEXT UNIQUE;
CREATE UNIQUE INDEX supplier_invoice_unique ON purchases(supplier_id,supplier_invoice_no,supplier_invoice_date) WHERE supplier_invoice_no IS NOT NULL;
ALTER TABLE purchase_orders ADD COLUMN items JSONB NOT NULL DEFAULT '[]';
ALTER TABLE purchase_orders ADD COLUMN expected_date DATE;
ALTER TABLE purchase_orders ADD COLUMN notes TEXT;
ALTER TABLE purchase_items ADD COLUMN snapshot JSONB;
ALTER TABLE purchase_items ADD COLUMN cgst_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchase_items ADD COLUMN sgst_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchase_items ADD COLUMN igst_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchase_items ADD COLUMN cess_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchases ADD COLUMN store_snapshot JSONB;
ALTER TABLE sales ADD COLUMN business_date DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE sales ADD COLUMN place_of_supply VARCHAR(2);
ALTER TABLE sales ADD COLUMN customer_snapshot JSONB;
ALTER TABLE sales ADD COLUMN store_snapshot JSONB;
ALTER TABLE sales ADD COLUMN cess_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN notes TEXT;
ALTER TABLE sales ADD COLUMN idempotency_key TEXT UNIQUE;
ALTER TABLE sale_items ADD COLUMN snapshot JSONB;
ALTER TABLE sale_items ADD COLUMN cgst_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE sale_items ADD COLUMN sgst_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE sale_items ADD COLUMN igst_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE sale_items ADD COLUMN cess_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN cess_rate NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD CONSTRAINT product_prices_positive CHECK(cost_price>=0 AND mrp>=0 AND sale_price>=0 AND sale_price<=mrp AND gst_rate BETWEEN 0 AND 100);
ALTER TABLE payments ADD COLUMN store_id INT REFERENCES stores(id);
ALTER TABLE payments ADD COLUMN payment_date DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE payments ADD COLUMN reference TEXT;
ALTER TABLE payments ADD COLUMN idempotency_key TEXT UNIQUE;
ALTER TABLE sales_returns ADD COLUMN sale_item_id INT REFERENCES sale_items(id);
ALTER TABLE sales_returns ADD COLUMN taxable_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE sales_returns ADD COLUMN gst_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE sales_returns ADD COLUMN refund_mode TEXT;
ALTER TABLE purchase_returns ADD COLUMN purchase_item_id INT REFERENCES purchase_items(id);
ALTER TABLE purchase_returns ADD COLUMN taxable_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchase_returns ADD COLUMN gst_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchase_returns ADD COLUMN refund_mode TEXT;
CREATE TABLE return_requests (request_key TEXT PRIMARY KEY, result JSONB NOT NULL);
CREATE TABLE held_bills (id SERIAL PRIMARY KEY, store_id INT NOT NULL REFERENCES stores(id), user_id INT NOT NULL REFERENCES users(id), name TEXT NOT NULL, payload JSONB NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE invoice_sequences (store_id INT NOT NULL REFERENCES stores(id), fy TEXT NOT NULL, kind TEXT NOT NULL, last_value INT NOT NULL DEFAULT 0, PRIMARY KEY(store_id,fy,kind));
CREATE TABLE gst_reconciliations (id SERIAL PRIMARY KEY, store_id INT NOT NULL REFERENCES stores(id), period TEXT NOT NULL, data JSONB NOT NULL, created_by INT REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE gst_transactions ALTER COLUMN transaction_type TYPE VARCHAR(20);
ALTER TABLE gst_transactions ADD COLUMN store_id INT REFERENCES stores(id);
ALTER TABLE gst_transactions ADD COLUMN cess_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE gst_transactions ADD COLUMN party_gstin VARCHAR(15);
ALTER TABLE gst_transactions ADD COLUMN place_of_supply VARCHAR(2);
ALTER TABLE gst_transactions ADD COLUMN invoice_number TEXT;
ALTER TABLE stock DROP CONSTRAINT stock_store_id_product_id_batch_id_key;
WITH totals AS (SELECT min(id) keep,sum(current_qty) qty,store_id,product_id FROM stock WHERE batch_id IS NULL GROUP BY store_id,product_id)
UPDATE stock s SET current_qty=t.qty FROM totals t WHERE s.id=t.keep;
DELETE FROM stock a USING stock b WHERE a.batch_id IS NULL AND b.batch_id IS NULL AND a.store_id=b.store_id AND a.product_id=b.product_id AND a.id>b.id;
ALTER TABLE stock ADD CONSTRAINT stock_unique UNIQUE NULLS NOT DISTINCT(store_id,product_id,batch_id);
ALTER TABLE stock ADD CONSTRAINT stock_nonnegative CHECK(current_qty>=0);
ALTER TABLE customers ALTER COLUMN opt_in_marketing SET DEFAULT false;
INSERT INTO permissions(module,action,code,description) VALUES
('expenses','manage','expenses.manage','Add and view expenses'),('payments','manage','payments.manage','Record receipts and supplier payments'),
('purchases','return','purchases.return','Return purchased goods'),('imports','manage','imports.manage','Review and commit imports'),
('inventory','transfer','inventory.transfer','Transfer stock between stores') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name IN ('admin','manager') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name='accountant' AND p.code IN('expenses.manage','payments.manage') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name='inventory_manager' AND p.code IN('inventory.transfer','imports.manage','purchases.return') ON CONFLICT DO NOTHING;
